[package]
name = "str8ts_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
log = "0.4.19"
solver = { path = "../solver" }
clap = { version = "4.3.19", features = ["derive"] }
